In [1]:
import pandas as pd
import os
import shutil
from sklearn.model_selection import train_test_split

In [2]:
# main directory
path = "/Users/ritvikraina/Library/Mobile Documents/com~apple~CloudDocs/College/Courses/CS4465 Bioinformatics/Project/data/dataset3"

In [3]:
# Create train and test directories
train_path = os.path.join(path,'train')
test_path = os.path.join(path,'test')

In [4]:
#sub-directories
covid_train_path = os.path.join(train_path,'Covid')
normal_train_path = os.path.join(train_path,'Normal')


covid_test_path = os.path.join(test_path,'Covid')
normal_test_path = os.path.join(test_path,'Normal')

In [5]:
covid_df = pd.read_csv(os.path.join(path,"meta_data_covid.csv"),encoding="windows-1252")
normal_df = pd.read_csv(os.path.join(path,"meta_data_normal.csv"),encoding="windows-1252")

In [6]:
covid_df.head()

,index,File name,Patient ID,Gender,Age,Country,Diagnosis,Slice,Case Discussion,Case Number,...,in_icu,intubated,intubation_present,license,mAs,mask_file,needed_supplemental_O2,study_file,survival,went_icu
0,0,6_Rahimzadeh_137covid_patient101_SR_4_IM00006.png,patient101,F,51,Iran,COVID-19,6.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1,6_Rahimzadeh_137covid_patient101_SR_4_IM00008.png,patient101,F,51,Iran,COVID-19,8.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2,6_Rahimzadeh_137covid_patient101_SR_4_IM00009.png,patient101,F,51,Iran,COVID-19,9.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,3,6_Rahimzadeh_137covid_patient101_SR_4_IM00010.png,patient101,F,51,Iran,COVID-19,10.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,4,6_Rahimzadeh_137covid_patient101_SR_4_IM00011.png,patient101,F,51,Iran,COVID-19,11.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [7]:
covid_df.drop(['Patient ID', 'Gender', 'Age', 'Country','Slice','Case Discussion', 'Case Number', 'Columns',
       'Date', 'Date of Last Calibration', 'Distance Source to Detector',
       'Distance Source to Patient', 'Exposure Time', 'Image Source',
       'Institution', 'KVP', 'Last Calibration', 'Link', 'Link2',
       'Other diseases', 'Presentation', 'RT_PCR_COVID-19', 'Rows', 'Severity',
       'Slice Thickness', 'Slices', 'Source_detail', 'Time', 'XRayTubeCurrent',
       'category', 'doi', 'finding', 'in_icu', 'intubated',
       'intubation_present', 'license', 'mAs', 'mask_file',
       'needed_supplemental_O2', 'study_file', 'survival', 'went_icu'],axis=1,inplace=True)

In [8]:
covid_df

      index                                          File name Diagnosis
0         0  6_Rahimzadeh_137covid_patient101_SR_4_IM00006.png  COVID-19
1         1  6_Rahimzadeh_137covid_patient101_SR_4_IM00008.png  COVID-19
2         2  6_Rahimzadeh_137covid_patient101_SR_4_IM00009.png  COVID-19
3         3  6_Rahimzadeh_137covid_patient101_SR_4_IM00010.png  COVID-19
4         4  6_Rahimzadeh_137covid_patient101_SR_4_IM00011.png  COVID-19
...     ...                                                ...       ...
7588   3810                                        P044_21.png  COVID-19
7589   3811                                        P044_15.png  COVID-19
7590   3812                                       P044_144.png  COVID-19
7591   3813                                         P044_6.png  COVID-19
7592   3814                                        P044_17.png  COVID-19

[7593 rows x 3 columns]

In [9]:
normal_df.drop(['index', 'Patient ID', 'Gender', 'Age', 'Country', 'Slice', 'Case Discussion', 'Case Number', 'Columns',
       'Date', 'Date of Last Calibration', 'Distance Source to Detector',
       'Distance Source to Patient', 'Exposure Time', 'Image Source',
       'Institution', 'KVP', 'Last Calibration', 'Link', 'Link2',
       'Other diseases', 'Presentation', 'RT_PCR_positive', 'Rows', 'Severity',
       'Slice Thickness', 'Slices', 'Source_detail', 'Time', 'XRayTubeCurrent',
       'category', 'doi', 'finding', 'in_icu', 'intubated',
       'intubation_present', 'license', 'mAs', 'mask_file',
       'needed_supplemental_O2', 'study_file', 'survival', 'went_icu'],axis=1,inplace=True)

In [10]:
normal_df

                                              File name Diagnosis
0     6_Rahimzadeh_normal10_patient151_SR_4_IM00012.png    Normal
1     6_Rahimzadeh_normal10_patient151_SR_4_IM00017.png    Normal
2     6_Rahimzadeh_normal10_patient151_SR_4_IM00022.png    Normal
3     6_Rahimzadeh_normal10_patient152_SR_4_IM00012.png    Normal
4     6_Rahimzadeh_normal10_patient152_SR_4_IM00017.png    Normal
...                                                 ...       ...
6888                                  normal010_136.png    Normal
6889                                  normal010_134.png    Normal
6890                                  normal010_121.png    Normal
6891                                  normal010_118.png    Normal
6892                                  normal010_125.png    Normal

[6893 rows x 2 columns]

In [11]:
df = pd.concat([normal_df,covid_df],ignore_index=True)
df

                                               File name Diagnosis   index
0      6_Rahimzadeh_normal10_patient151_SR_4_IM00012.png    Normal     NaN
1      6_Rahimzadeh_normal10_patient151_SR_4_IM00017.png    Normal     NaN
2      6_Rahimzadeh_normal10_patient151_SR_4_IM00022.png    Normal     NaN
3      6_Rahimzadeh_normal10_patient152_SR_4_IM00012.png    Normal     NaN
4      6_Rahimzadeh_normal10_patient152_SR_4_IM00017.png    Normal     NaN
...                                                  ...       ...     ...
14481                                        P044_21.png  COVID-19  3810.0
14482                                        P044_15.png  COVID-19  3811.0
14483                                       P044_144.png  COVID-19  3812.0
14484                                         P044_6.png  COVID-19  3813.0
14485                                        P044_17.png  COVID-19  3814.0

[14486 rows x 3 columns]

In [12]:
# Images and Labels
x = df.loc[:,'File name']
y = df.loc[:,'Diagnosis']

# Train-Test splitfor train and validation images
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.1, stratify=y)

In [13]:
# Train df
df_train = pd.DataFrame(columns=['Image','Diagnosis'])
df_train['Image'] = x_train
df_train['Diagnosis'] = y_train

# Test df
df_test= pd.DataFrame(columns=['Image','Diagnosis'])
df_test['Image'] = x_test
df_test['Diagnosis'] = y_test

# Reset index
df_train.reset_index(drop=True, inplace=True)
df_test.reset_index(drop=True, inplace=True)

In [14]:
# Save train images
for i in range(len(df_train)):

    image = df_train.loc[i,'Image']

    if df_train.loc[i,'Diagnosis'] == "Normal":
        shutil.copy(path + '/curated_data/Normal/' + image, normal_train_path)
    else:
        shutil.copy(path + '/curated_data/Covid/' + image, covid_train_path)

In [15]:
# Save test images
for i in range(len(df_test)):

    image = df_test.loc[i,'Image']

    if df_test.loc[i,'Diagnosis'] == "Normal":
        shutil.copy(path + '/curated_data/Normal/' + image, normal_test_path)
    else:
        shutil.copy(path + '/curated_data/Covid/' + image, covid_test_path)

In [17]:
len(os.listdir(normal_test_path))

689

In [19]:
df_train.to_csv("dataset2_train")

                                                 Image Diagnosis
0                         16_Morozov_study_0204_15.png    Normal
1                         16_Morozov_study_0097_14.png    Normal
2                                         P007_140.png  COVID-19
3                                         P104_159.png  COVID-19
4                                    normal003_154.png    Normal
...                                                ...       ...
1444                      16_Morozov_study_0175_20.png    Normal
1445  6_Rahimzadeh_normal4_patient218_SR_4_IM00020.png    Normal
1446                                      P058_131.png  COVID-19
1447                                       P028_90.png  COVID-19
1448                 14_Jun_coronacases_case10_131.png  COVID-19

[1449 rows x 2 columns]